# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainGUI.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(611, 249)
        MainWindow.setMinimumSize(QtCore.QSize(611, 249))
        MainWindow.setMaximumSize(QtCore.QSize(611, 249))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 208))
        self.centralwidget.setMaximumSize(QtCore.QSize(611, 208))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.StatusLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.StatusLabel.setFont(font)
        self.StatusLabel.setText("")
        self.StatusLabel.setObjectName("StatusLabel")
        self.verticalLayout.addWidget(self.StatusLabel, 0, QtCore.Qt.AlignHCenter)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.TopicLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.TopicLabel.setFont(font)
        self.TopicLabel.setStyleSheet("min-width:55px;\n"
"max-width:55px;")
        self.TopicLabel.setObjectName("TopicLabel")
        self.horizontalLayout_4.addWidget(self.TopicLabel)
        self.TopicLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.TopicLineEdit.setObjectName("TopicLineEdit")
        self.horizontalLayout_4.addWidget(self.TopicLineEdit)
        self.LanguageLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.LanguageLabel.setFont(font)
        self.LanguageLabel.setStyleSheet("margin-left:20px")
        self.LanguageLabel.setObjectName("LanguageLabel")
        self.horizontalLayout_4.addWidget(self.LanguageLabel)
        self.LanguageLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.LanguageLineEdit.setObjectName("LanguageLineEdit")
        self.horizontalLayout_4.addWidget(self.LanguageLineEdit, 0, QtCore.Qt.AlignVCenter)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.ApplayButton = QtWidgets.QPushButton(self.centralwidget)
        self.ApplayButton.setObjectName("ApplayButton")
        self.verticalLayout.addWidget(self.ApplayButton, 0, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Speeker1Label = QtWidgets.QLabel(self.centralwidget)
        self.Speeker1Label.setStyleSheet("min-width:55px;\n"
"max-width:55px;")
        self.Speeker1Label.setObjectName("Speeker1Label")
        self.horizontalLayout_2.addWidget(self.Speeker1Label)
        self.Speeker1Result = QtWidgets.QLabel(self.centralwidget)
        self.Speeker1Result.setText("")
        self.Speeker1Result.setObjectName("Speeker1Result")
        self.horizontalLayout_2.addWidget(self.Speeker1Result)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Speeker2Label = QtWidgets.QLabel(self.centralwidget)
        self.Speeker2Label.setStyleSheet("min-width:55px;\n"
"max-width:55px;")
        self.Speeker2Label.setObjectName("Speeker2Label")
        self.horizontalLayout_3.addWidget(self.Speeker2Label)
        self.Speeker2Result = QtWidgets.QLabel(self.centralwidget)
        self.Speeker2Result.setText("")
        self.Speeker2Result.setObjectName("Speeker2Result")
        self.horizontalLayout_3.addWidget(self.Speeker2Result)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.Speeker1Button = QtWidgets.QPushButton(self.centralwidget)
        self.Speeker1Button.setObjectName("Speeker1Button")
        self.horizontalLayout.addWidget(self.Speeker1Button)
        self.Speeker2Button = QtWidgets.QPushButton(self.centralwidget)
        self.Speeker2Button.setObjectName("Speeker2Button")
        self.horizontalLayout.addWidget(self.Speeker2Button)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 611, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Transcriptor"))
        self.TopicLabel.setText(_translate("MainWindow", "Topic:"))
        self.LanguageLabel.setText(_translate("MainWindow", "Language"))
        self.ApplayButton.setText(_translate("MainWindow", "Applay"))
        self.Speeker1Label.setText(_translate("MainWindow", "Speeker 1: "))
        self.Speeker2Label.setText(_translate("MainWindow", "Speeker 2: "))
        self.Speeker1Button.setText(_translate("MainWindow", "Speeker 1"))
        self.Speeker2Button.setText(_translate("MainWindow", "Speeker 2"))
import imgs_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
